image: node:15-alpine
stages:
  - docker

build-docker:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
    CRYPTOGRAPHY_DONT_BUILD_RUST: 1
  services:
  - docker:dind
  stage: docker
  environment: staging
  script:
    - echo "Build docker 🐳"
    - docker build . -t=reminder-app:glb-${CI_PIPELINE_IID}